#ifndef LOCALIZATION_H
#define LOCALIZATION_H

#include <stdbool.h>
#include <windows.h>

typedef enum {
    LOC_APP_TITLE,
    LOC_STATUS_LN_COL,
    LOC_STATUS_SIZE,
    LOC_STATUS_ENCODING_UNKNOWN,
    LOC_STATUS_ENCODING_UTF8,
    LOC_STATUS_ENCODING_UTF16_LE,
    LOC_STATUS_ENCODING_UTF16_BE,
    LOC_STATUS_ENCODING_ANSI,
    LOC_MENU_FILE,
    LOC_MENU_NEW_TAB,
    LOC_MENU_CLOSE_TAB,
    LOC_MENU_NEW,
    LOC_MENU_OPEN,
    LOC_MENU_SAVE,
    LOC_MENU_SAVE_AS,
    LOC_MENU_PRINT,
    LOC_MENU_EXPORT_PDF,
    LOC_MENU_RECENT_FILES,
    LOC_MENU_EXIT,
    LOC_MENU_EDIT,
    LOC_MENU_UNDO,
    LOC_MENU_FIND,
    LOC_MENU_REPLACE,
    LOC_MENU_GOTO,
    LOC_MENU_CUT,
    LOC_MENU_COPY,
    LOC_MENU_PASTE,
    LOC_MENU_SELECT_ALL,
    LOC_MENU_VIEW,
    LOC_MENU_ALWAYS_ON_TOP,
    LOC_MENU_SYNTAX_HIGHLIGHT,
    LOC_MENU_LANGUAGE_MODE,
    LOC_MENU_LANGUAGE_PLAIN,
    LOC_MENU_LANGUAGE_C,
    LOC_MENU_LANGUAGE,
    LOC_MENU_LANG_ENGLISH,
    LOC_MENU_LANG_BANGLA,
    LOC_MENU_OPTIONS,
    LOC_MENU_AUTOSAVE,
    LOC_MENU_LINE_ENDINGS,
    LOC_MENU_LINE_ENDINGS_CRLF,
    LOC_MENU_LINE_ENDINGS_LF,
    LOC_MENU_ENCODING,
    LOC_MENU_ENCODING_UTF8,
    LOC_MENU_ENCODING_UTF16_LE,
    LOC_MENU_ENCODING_UTF16_BE,
    LOC_MENU_ENCODING_ANSI,
    LOC_KEY_COUNT
} LocKey;

void localization_init(void);
void localization_set_bangla(bool enable);
bool localization_is_bangla(void);

const wchar_t *loc_wstr(LocKey key);

#endif
